name: SAO-MCPE
version: 1.0
main: NetherTechnology\SAO-System\Main
author: NetherTechnology
api: 3.0.0

commands:
   sao:
        usage: /sao <help | commands>
		description: SAO-System Main Command
   lang:
        usage: /lang <en>
		description: Choose the Lang
