name: SAO-System
version: 1.0
main: NetherTechnology\SAO\Main
author: MangoTheDev
api: 3.0.0-ALPHA11

commands:
   sao:
        usage: /sao <help | commands
        description: The SAO Main Commands
