name: SAO-MCPE
version: 1.0
main: NetherTechnology\SAO\Main
author: NetherTechnology
api: 3.0.0

commands:
   sao:
        usage: /sao <help | commands>
	description: SAO-System Main Command
   login:
        usage: /login <help | commands>
	descritpiom: SAO Login System Main Command
   lang:
        usage: /lang <en>
	description: Choose the Lang
